runtime: python311

entrypoint: gunicorn -b :$PORT app:app  # Command to run your app (adjust "app:app" as needed)

instance_class: F2  # Optional: specify instance class

handlers:  # Define routing
  - url: /.*
    script: auto
